### ISSUE TITLE
minTime, maxTime features (like I used in duDatepicker) to block time, i.e falling into past.

### ISSUE THREAD

**Issue by daranaveen007** [dmuy/MDTimePicker#1]
Please help me to get this feature as much as faster you can update. Thanks!! Appreciation.

**Comment by daranaveen007** [comment]
Dear author, please implement these features minTime(data-mintime), maxTime(data-maxtime). So, that many people will get helped as like me.

**Comment by dmuy** [comment]
Hi @daranaveen007,

Actually I've thought about this kind of feature before publishing the plugin here, but it's quite complicated to implement really. Honestly, I have no idea yet how to implement this feature because there are a lot of things to consider for disabling the hour and minute digits, like the input flow of the time picker - it's not straightforward like the date picker. And I'm a bit busy with work.

I would also love to have this feature in the plugin because I also use my plugins, but time is not with me right now.

**Comment by dmuy** [comment]
This enhancement is now available on this [commit](https://github.com/dmuy/MDTimePicker/commit/c5082c6679d225c2bee1ab14f8b00fa732a2c2de)
