### ISSUE TITLE
Show Minutes Only

### ISSUE THREAD

**Issue by shafaqat309** [dmuy/MDTimePicker#9]
What options I need to pass to show minutes only selector?
I want user to choose minutes form 0 to 59.

**Comment by dmuy** [comment]
Hi @shafaqat309,

The plugin doesn't have an option to "only" show minutes since it's a time picker. But you can click on the minute placeholder (in the header section; time placeholder) to show the minute selector (as shown on the 2nd image in the [ReadMe](https://github.com/dmuy/MDTimePicker/blob/master/README.md) file).

**Comment by shafaqat309** [comment]
Can I show minute placeholder selected by default? Currently hour placeholder is selected by default.

**Comment by shafaqat309** [comment]
I have done that finally, 

![image](https://user-images.githubusercontent.com/2289283/86094901-796a0800-baf4-11ea-832a-9f78efb8e036.png)

If you think, it can be consider as a feature, then let me know and I will raise a PR. You can adjust my code to make to more user friendly but for the time being it works for me.

**Comment by dmuy** [comment]
Hi @shafaqat309,

It's good that you worked it out. Maybe I can add an option to show the minute selector by default like `defaultView` or something. But I will not remove the hour selector as it would defeat the name of the plugin.

Thanks
